added customization of export/import data via user defined functions
django-cms/djangocms-transfer pull request #20
Opened 2021-05-26 05:34 UTC by wfehr

Implementing a general handling for all different plugins around is tough to implement, if even possible.
The easiest way is to let the user implement custom code for his purposes when exporting and importing.
This makes export/import between different systems available.

2021-05-26 06:35 UTC, goutnet commented
Hi, generally, you should target `develop` branch not `master` please rebase & re-target.

2021-05-26 06:36 UTC, goutnet requested changes
please target `develop` for PR before we can review.

2023-01-13 09:18 UTC, wfehr commented
any news on this one?

2023-01-13 09:35 UTC, fsbraun approved these changes
Sorry, this took such a long time. I assume you are tweaking third party plugins this way?

2023-01-13 09:44 UTC, wfehr commented
> Sorry, this took such a long time. I assume you are tweaking third party plugins this way?

Yes, with the changes added here I can use the project to import/export plugins between different systems.
Because of the "mass of different plugins" it is not that easy to implement a general processing of plugins.

For example: django-filer content would currently result in not being able to import/export between systems.
But with adding individual code in my project which handles filer-dependencies I can achieve this.

2023-07-27 14:56 UTC, merged